version: '3.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - '8090:80'
    volumes:
      - ./templates:/etc/nginx/conf.d
      - ./netcat:/netcat
    environment:
      - NGINX_HOST=mytest.com
      - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']
